- name: Demo on filters
  hosts: all
  vars:
    URL: https://github.com/zelar-soft-roboshop/frontend/archive/main.zip
    tag_data:
          Environment: dev
          Application: payment
  tasks:
    - name: Print filename of a url
      debug:
        msg: "{{ URL | urlsplit }}"

    - name: Print last colum
      debug:
        msg: "{{ URL.split('/') | last }}"

    - name: Print tag data
      debug:
        msg: "{{ tag_data | dict2items }}"

    - name: Create servers
      debug:
        msg: "{{ item.name }}"
      loop:
        - name: server1
          disks: 3gb
          ram: 15Gb
          network:
            nic01: 100Gb
            nic02: 10Gb
        - name: server2
          disks: 3gb
          ram: 15Gb
          network:
            nic01: 100Gb
            nic02: 10Gb
#      loop_control:
#        label: "{{ item.name }}"