- name: Setup roboshop project
  hosts: all
  become: yes
  ## THis become can also be used at task level
  roles:
    - role: frontend
      tags: frontend
      when: COMPONENT == "frontend"

    - role: mongodb
      tags: mongodb
      when: COMPONENT == "mongodb"

    - role: catalogue
      tags: catalogue
      when: COMPONENT == "catalogue"

