- name: Setup roboshop project
  hosts: all
  become: yes
  ## THis become can also be used at task level
  tasks:
    - name: Install Nginx
      apt:
        name: nginx
        update_cache: yes
        state: present

