- name: Check the status of Docker Service
  shell: systemctl status docker
  register: out

- name: Install Docker
  shell: curl -s https://get.docker.com | bash
  when: out.rc != 0

- name: Start Docker
  systemd:
    enabled: yes
    state: started
    name: docker

- name: Install Pip3
  apt:
    name: python3-pip
    state: present
    update_cache: yes

- name: Create MySQL Data directory
  file:
    path: /data
    state: directory

#- name: Create a MySQL container
#  docker_container:
#    name: mysql
#    image: mysql:5.7.33
#    volumes:
#      - "/data:/var/lib/mysql"
#    ports:
#      - "3306:3306"
#    env:
#      MYSQL_ROOT_PASSWORD: "password"

