- name: Install NPM
  apt:
    name: npm
    state: present
    update_cache: yes

- name: Add roboshop user
  user:
    name: roboshop
    shell: /bin/bash

- name: Download Cart from Nexus
  get_url:
    url: http://172.31.14.124:8081/repository/cart/cart-{{APP_VERSION}}.zip
    dest: /tmp/cart.zip
    username: admin
    password: admin123

- name: Clean the old artifacts
  file:
    path: /home/roboshop/cart
    state: absent

- name: Create the artifact path
  file:
    path: /home/roboshop/cart
    state: directory
    owner: roboshop
    group: roboshop

- name: Extract the Cart Content
  unarchive:
    src: /tmp/cart.zip
    dest: /home/roboshop/cart
    remote_src: yes
    owner: roboshop
    group: roboshop

- name: Copy Cart Service file
  copy:
    src: cart.service
    dest: /etc/systemd/system/cart.service

- name: Start Cart Service
  systemd:
    name: cart
    daemon_reload: yes
    state: started
    enabled: yes




